title: Bobby's Cookbook
description: A place for my study notes
theme: just-the-docs
logo: "/assets/images/logo.png"


url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
  recipes:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    recipes:
      name: Recipes